-- ShopVerse: 50 additional products (run after 02_seed.sql on existing DB)
-- Brings catalog from 12 → 62 items for search, AI, and price-filter testing.
-- Demo images cycle through /products/1.jpg … /products/12.jpg

INSERT INTO products (id, name, price, category, rating, image, description, badge, vibes) VALUES
(13, 'Bluetooth Speaker Mini', 89.99, 'Electronics', 4.5,
 '/products/13.svg',
 'Palm-sized speaker with 12-hour battery and rich bass for desk or picnic table.',
 NULL, '{"focus":55,"motion":70,"nest":60,"signal":65}'::jsonb),
(14, 'USB-C Hub 7-in-1', 64.50, 'Electronics', 4.4,
 '/products/14.svg',
 'HDMI, SD, and three USB ports in one compact dock for laptop workflows.',
 'New', '{"focus":88,"motion":25,"nest":45,"signal":40}'::jsonb),
(15, 'Mechanical Keyboard TKL', 145.00, 'Electronics', 4.7,
 '/products/15.svg',
 'Tactile switches and hot-swap caps for long typing sessions without wrist fatigue.',
 'Best Seller', '{"focus":95,"motion":30,"nest":50,"signal":55}'::jsonb),
(16, 'Webcam HD Pro', 78.00, 'Electronics', 4.3,
 '/products/16.svg',
 '1080p autofocus camera with built-in ring light for crisp video calls.',
 NULL, '{"focus":82,"motion":20,"nest":40,"signal":48}'::jsonb),
(17, 'Portable Charger 20K', 52.99, 'Electronics', 4.6,
 '/products/17.svg',
 'Fast-charge power bank that keeps phone and earbuds alive through travel days.',
 'Sale', '{"focus":40,"motion":85,"nest":35,"signal":45}'::jsonb),
(18, 'Noise-Blocking Earbuds', 119.00, 'Electronics', 4.8,
 '/products/18.svg',
 'In-ear ANC with transparency mode for commute focus and gym sessions.',
 'Top Rated', '{"focus":90,"motion":75,"nest":30,"signal":70}'::jsonb),
(19, 'Smart Plug 4-Pack', 39.99, 'Electronics', 4.2,
 '/products/19.svg',
 'Voice-controlled outlets to automate lamps, fans, and morning routines.',
 NULL, '{"focus":60,"motion":15,"nest":80,"signal":35}'::jsonb),
(20, 'E-Reader Stand', 34.00, 'Electronics', 4.4,
 '/products/20.svg',
 'Adjustable aluminum holder for tablets and e-readers at the perfect angle.',
 NULL, '{"focus":85,"motion":10,"nest":75,"signal":30}'::jsonb),
(21, 'Ergonomic Wireless Mouse', 58.00, 'Electronics', 4.5,
 '/products/21.svg',
 'Vertical grip design that reduces strain during all-day desk work.',
 NULL, '{"focus":92,"motion":20,"nest":55,"signal":38}'::jsonb),
(22, 'Monitor Light Bar', 72.00, 'Electronics', 4.6,
 '/products/22.svg',
 'Screen-mounted lamp that lights your desk without glare on the monitor.',
 'New', '{"focus":94,"motion":15,"nest":70,"signal":42}'::jsonb),
(23, 'Slim Chino Pants', 88.00, 'Clothing', 4.5,
 '/products/23.svg',
 'Tailored stretch chinos that move from office to dinner without a change.',
 NULL, '{"focus":65,"motion":60,"nest":55,"signal":78}'::jsonb),
(24, 'Merino Wool Beanie', 32.00, 'Clothing', 4.4,
 '/products/24.svg',
 'Soft, breathable beanie for cold commutes and weekend walks.',
 NULL, '{"focus":35,"motion":70,"nest":85,"signal":50}'::jsonb),
(25, 'Performance Running Shorts', 45.00, 'Clothing', 4.7,
 '/products/25.svg',
 'Lightweight liner shorts with zip pocket for keys on tempo runs.',
 'Top Rated', '{"focus":30,"motion":98,"nest":25,"signal":55}'::jsonb),
(26, 'Linen Button-Down Shirt', 74.00, 'Clothing', 4.6,
 '/products/26.svg',
 'Breathable linen that looks polished even on humid travel days.',
 'New', '{"focus":50,"motion":65,"nest":70,"signal":82}'::jsonb),
(27, 'Fleece Quarter-Zip', 69.00, 'Clothing', 4.5,
 '/products/27.svg',
 'Mid-weight layer for morning jogs and couch evenings alike.',
 NULL, '{"focus":45,"motion":72,"nest":88,"signal":48}'::jsonb),
(28, 'Compression Leggings', 56.00, 'Clothing', 4.6,
 '/products/28.svg',
 'Supportive stretch fabric for yoga, training, and recovery days.',
 NULL, '{"focus":40,"motion":95,"nest":50,"signal":60}'::jsonb),
(29, 'Light Wash Denim Jacket', 98.00, 'Clothing', 4.5,
 '/products/29.svg',
 'Classic cut denim that layers over tees and dresses year-round.',
 'Limited', '{"focus":42,"motion":55,"nest":58,"signal":90}'::jsonb),
(30, 'Cashmere Scarf', 110.00, 'Clothing', 4.8,
 '/products/30.svg',
 'Fine-knit scarf that adds quiet luxury to any winter outfit.',
 NULL, '{"focus":38,"motion":30,"nest":92,"signal":88}'::jsonb),
(31, 'Packable Rain Shell', 125.00, 'Clothing', 4.7,
 '/products/31.svg',
 'Waterproof jacket that folds into its own pocket for trail and travel.',
 'Best Seller', '{"focus":35,"motion":92,"nest":40,"signal":65}'::jsonb),
(32, 'Everyday Crew Socks 3-Pack', 24.00, 'Clothing', 4.3,
 '/products/32.svg',
 'Cushioned cotton socks that hold up wash after wash.',
 'Sale', '{"focus":25,"motion":60,"nest":75,"signal":30}'::jsonb),
(33, 'Weighted Throw Blanket', 89.00, 'Home', 4.6,
 '/products/33.svg',
 '12 lb blanket that helps you unwind and sleep deeper on restless nights.',
 NULL, '{"focus":70,"motion":10,"nest":97,"signal":35}'::jsonb),
(34, 'Bamboo Cutting Board Set', 48.00, 'Home', 4.5,
 '/products/34.svg',
 'Three sized boards that protect knives and look good on the counter.',
 NULL, '{"focus":55,"motion":15,"nest":90,"signal":40}'::jsonb),
(35, 'Scented Candle Trio', 36.00, 'Home', 4.4,
 '/products/35.svg',
 'Sandalwood, cedar, and vanilla candles for slow evening rituals.',
 'New', '{"focus":60,"motion":12,"nest":95,"signal":50}'::jsonb),
(36, 'Ceramic Mug Set of 4', 42.00, 'Home', 4.5,
 '/products/36.svg',
 'Matte glaze mugs sized for coffee, tea, and weekend cocoa.',
 NULL, '{"focus":65,"motion":10,"nest":93,"signal":38}'::jsonb),
(37, 'Walnut Desk Organizer', 55.00, 'Home', 4.6,
 '/products/37.svg',
 'Slots for pens, phone, and notes to keep a clean focus zone.',
 NULL, '{"focus":91,"motion":12,"nest":80,"signal":35}'::jsonb),
(38, 'Essential Oil Diffuser', 47.00, 'Home', 4.4,
 '/products/38.svg',
 'Ultrasonic mist with warm light for calm mornings and wind-down.',
 NULL, '{"focus":72,"motion":8,"nest":96,"signal":42}'::jsonb),
(39, 'Linen Pillowcase Pair', 58.00, 'Home', 4.7,
 '/products/39.svg',
 'Cool-to-touch linen that gets softer with every wash.',
 'Top Rated', '{"focus":50,"motion":10,"nest":94,"signal":45}'::jsonb),
(40, 'Glass French Press', 38.00, 'Home', 4.5,
 '/products/40.svg',
 'Borosilicate press for rich coffee without paper filters.',
 NULL, '{"focus":68,"motion":15,"nest":92,"signal":40}'::jsonb),
(41, 'Indoor Herb Garden Kit', 65.00, 'Home', 4.6,
 '/products/41.svg',
 'LED grow light and pots for basil, mint, and parsley on the windowsill.',
 'New', '{"focus":58,"motion":18,"nest":91,"signal":48}'::jsonb),
(42, 'Minimal Wall Clock', 44.00, 'Home', 4.4,
 '/products/42.svg',
 'Silent sweep movement with a clean dial for distraction-free rooms.',
 NULL, '{"focus":80,"motion":10,"nest":85,"signal":55}'::jsonb),
(43, 'Trail Running Shoes', 145.00, 'Footwear', 4.8,
 '/products/43.svg',
 'Aggressive grip and rock plate for muddy paths and rocky climbs.',
 'Best Seller', '{"focus":28,"motion":99,"nest":20,"signal":72}'::jsonb),
(44, 'Suede Chelsea Boots', 198.00, 'Footwear', 4.7,
 '/products/44.svg',
 'Pull-on boots with cushioned sole for smart casual and travel.',
 'Limited', '{"focus":45,"motion":50,"nest":55,"signal":94}'::jsonb),
(45, 'Canvas Sneakers Low', 72.00, 'Footwear', 4.5,
 '/products/45.svg',
 'Everyday sneakers with vulcanized sole and broken-in feel from day one.',
 NULL, '{"focus":40,"motion":68,"nest":65,"signal":75}'::jsonb),
(46, 'Waterproof Hiking Boots', 175.00, 'Footwear', 4.8,
 '/products/46.svg',
 'GORE-TEX lining and ankle support for multi-day trail trips.',
 'Top Rated', '{"focus":25,"motion":98,"nest":22,"signal":68}'::jsonb),
(47, 'Leather House Loafers', 95.00, 'Footwear', 4.6,
 '/products/47.svg',
 'Soft leather slip-ons for working from home and quick errands.',
 NULL, '{"focus":55,"motion":35,"nest":88,"signal":70}'::jsonb),
(48, 'Cross-Training Shoes', 128.00, 'Footwear', 4.7,
 '/products/48.svg',
 'Stable platform for lifts, sprints, and studio classes.',
 NULL, '{"focus":35,"motion":96,"nest":28,"signal":78}'::jsonb),
(49, 'Comfort Strap Sandals', 58.00, 'Footwear', 4.4,
 '/products/49.svg',
 'Arch-support sandals for beach days and post-hike recovery.',
 'Sale', '{"focus":20,"motion":65,"nest":82,"signal":45}'::jsonb),
(50, 'Insulated Winter Boots', 165.00, 'Footwear', 4.7,
 '/products/50.svg',
 'Fleece-lined boots rated for snow commutes and cold dog walks.',
 NULL, '{"focus":22,"motion":75,"nest":70,"signal":60}'::jsonb),
(51, 'Classic Ballet Flats', 68.00, 'Footwear', 4.5,
 '/products/51.svg',
 'Flexible flats that pair with dresses, denim, and office looks.',
 NULL, '{"focus":38,"motion":45,"nest":60,"signal":85}'::jsonb),
(52, 'Performance Socks 5-Pack', 28.00, 'Footwear', 4.4,
 '/products/52.svg',
 'Moisture-wicking socks with targeted cushion for runners.',
 NULL, '{"focus":25,"motion":90,"nest":40,"signal":35}'::jsonb),
(53, 'Titanium Slim Wallet', 45.00, 'Accessories', 4.5,
 '/products/53.svg',
 'RFID-blocking card holder that sits flat in front pockets.',
 NULL, '{"focus":70,"motion":55,"nest":45,"signal":80}'::jsonb),
(54, 'Polarized Sunglasses', 85.00, 'Accessories', 4.6,
 '/products/54.svg',
 'UV400 lenses with acetate frames for driving and outdoor brunch.',
 'New', '{"focus":35,"motion":70,"nest":40,"signal":88}'::jsonb),
(55, 'Classic Leather Belt', 62.00, 'Accessories', 4.5,
 '/products/55.svg',
 'Full-grain leather belt with brushed buckle for daily wear.',
 NULL, '{"focus":50,"motion":40,"nest":55,"signal":82}'::jsonb),
(56, 'Travel Toiletry Bag', 38.00, 'Accessories', 4.4,
 '/products/56.svg',
 'Water-resistant pouch with hang hook for gym and weekend trips.',
 NULL, '{"focus":45,"motion":80,"nest":50,"signal":55}'::jsonb),
(57, 'Silk Sleep Mask', 29.00, 'Accessories', 4.6,
 '/products/57.svg',
 'Blackout silk mask that blocks light for deeper naps and flights.',
 NULL, '{"focus":75,"motion":25,"nest":92,"signal":40}'::jsonb),
(58, 'Compact Gym Duffel', 78.00, 'Accessories', 4.5,
 '/products/58.svg',
 'Ventilated shoe compartment and wet pocket for post-workout gear.',
 NULL, '{"focus":30,"motion":93,"nest":35,"signal":62}'::jsonb),
(59, 'Magnetic Phone Ring Holder', 22.00, 'Accessories', 4.3,
 '/products/59.svg',
 'Snap-on grip and stand for one-handed scrolling and video calls.',
 'Sale', '{"focus":60,"motion":45,"nest":50,"signal":55}'::jsonb),
(60, 'Weekender Garment Bag', 92.00, 'Accessories', 4.6,
 '/products/60.svg',
 'Fold-over bag that keeps suits and dresses wrinkle-free on trips.',
 NULL, '{"focus":40,"motion":78,"nest":45,"signal":75}'::jsonb),
(61, 'Gold Hoop Earrings', 135.00, 'Accessories', 4.7,
 '/products/61.svg',
 '18K gold-plated hoops that elevate everyday and evening looks.',
 'Limited', '{"focus":30,"motion":35,"nest":50,"signal":96}'::jsonb),
(62, 'RFID Passport Wallet', 48.00, 'Accessories', 4.5,
 '/products/62.svg',
 'Slim travel wallet with passport slot and boarding-pass pocket.',
 NULL, '{"focus":42,"motion":88,"nest":38,"signal":70}'::jsonb)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
